### ISSUE TITLE
Frozen chart when NULL value provided

### ISSUE THREAD

**Issue by Willfriz** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#164]
We've noticed that when a NULL value has been identified, the chart freezing on it's last working presentation - this could lead to mis-reporting when changing between our services and it looks like the chart is presenting working data rather than erroring. The expected behaviour would be to ignore the NULL from calculations - rather than freezing the last working values.

**Comment by andrjohns** [comment]
Thanks for the report and apologies for the delay! This should be fixed in the latest [Development Build](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/releases/tag/latest) (v1.3.3.16). Would you be able to try it out and let me know if the visual still crashes/freezes for you?

**Comment by Willfriz** [comment]
Hi, Thanks for the prompt response - we have done a bit of testing and have not seen a change in the behaviour. We believe it is NULLs and low numbers having the freeze effect. A new issue as well is that in MS Edge we can no longer see the visual.

**Comment by andrjohns** [comment]
Are you able to share a dataset which reproduces this for you? Even just a CSV/xlsx export or similar so I can debug locally

**Comment by andrjohns** [comment]
@Willfriz I've updated the visual to now render an error message instead of a blank visual if the visual crashes on invalid data/etc., and also to flag whether the error is related to data issues or an internal visual bug. Would you mind trying out the latest development release to see whether it gives you any more information about the issue?

For example, if there's an issue with invalid inputs, then you'll see an error like this:
![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/8eac16c8-a410-488e-a554-bfcd80ed5662)

And if there's an internal visual bug, then you'll see an error like this:
![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/e90b4bdc-d0ff-4113-a55f-6a33dc88acbf)


Hope that helps, and let me know if there's anything else I can do to help debug!

**Comment by Willfriz** [comment]
Thanks @andrjohns , I'll get taking a look and respond as soon as possible.

**Comment by vickiriddio** [comment]
@andrjohns Thank you for this fix it works as expected. 

We are hoping to roll out this SPC chart across our trust once you have been published with Mictosoft Store. Any indications as to when this is likely to happen as we are very excited to get using the charts.

**Comment by andrjohns** [comment]
> @andrjohns Thank you for this fix it works as expected.

Great to hear! 

> We are hoping to roll out this SPC chart across our trust once you have been published with Mictosoft Store. Any indications as to when this is likely to happen as we are very excited to get using the charts.

I'm just working through a batch of issues/bugs identified by our team (#176), but we're aiming to submit early next week
