### ISSUE TITLE
Feature Request: Additional line setting options

### ISSUE THREAD

**Issue by alexmcqueen** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#213]
It would be great to have a few more line setting options.

1. The abilitly to toggle lines on and off the chart. Having lines for 99% limit (high and low), 95% limit (high and low) and centre line can crowd the graph. Often SPC are used by senior non-technical / non-mathematical members of staff and in some instances would help to de-clutter the chart. 
2. Abilitly to update line chart names shown on tooltip. Due to difference in terminologly used by statisitcians vs decision makers it would be helpful to be able to update the names used on the tooltip. Since only interested in tooltips for lines (for example Lower 99% could become LCL or Lower Control limit) it could sit in the line setting as an additional option.

**Comment by stuartbaxter24** [comment]
3. Would it also be possible to change the additional target value option (in data settings) so that this is a range of values rather than a fixed single value - i.e. if my target changes each month I would want the line to reflect this and adjust the assurance calculation and icon accordingly. 
4. Is it possible to show empty future dates so I can see the trajectory of my target line (as in the below picture)?

![spc](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/157391364/bdbeb46f-2a18-41fe-8428-c78f32809ee8)

**Comment by stuartbaxter24** [comment]
3. I have tried using the 'fx' conditional formatting using both formula and selecting a column of data. Both methods seem to still only bring back a single value.

4.  Apologies, I meant so I could see the additional target line (blue line in the picture above) (assuming this line could be shown as a changing value as in the point above).

**Comment by andrjohns** [comment]
@alexmcqueen The current development version now has added toggles for whether to display each line, whether to include the value in the tooltip, and the label to use in the tooltip:

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/622de696-3c91-4ded-9463-87d08bbdccce)


Let me know if that covers what you needed

**Comment by andrjohns** [comment]
@stuartbaxter24 

> 3. I have tried using the 'fx' conditional formatting using both formula and selecting a column of data. Both methods seem to still only bring back a single value.

Thanks for catching this! Definitely a bug (or more likely something I completely forgot I hadn't done yet :sweat_smile:). It should be fixed in the development release now, sorry for the bad advice!

> 4. Apologies, I meant so I could see the additional target line (blue line in the picture above) (assuming this line could be shown as a changing value as in the point above).

Oh I see what you mean. That's not possible at the moment unfortunately. Any input data with missing values for the outcome are filtered out during pre-processing so that they don't influence the calculation of control limits. I can have a look into an "allow trailing blanks" option or similar after the next AppSource release, but I'll have to think about the problem a bit more

**Comment by andrjohns** [comment]
@stuartbaxter24 Oh and a quick FYI that I moved the input box for the alt target lines to the `Line Settings` menu in the `Alt Target` dropdown, so that the grouping of settings is a bit more consistent

**Comment by alexmcqueen** [comment]
@andrjohns looks perfect thanks.
