### ISSUE TITLE
Outliers 

### ISSUE THREAD

**Issue by shs332000** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#263]
I am wondering what "Imp", "Det", "Neutral (Low)", and "Neutral (High)" means for outlier highlighting in my case. I am doing it on test results, where there is Upper and Lower specification limits, that aren't always equi-distant from the target value. (ex: the LSL could be 0, target value could be 30, and USL could be 100). What should I do for color highlighting in this example? I want to highlight the "out of control" points red so on the dashboard my maintenance team can see what test failed. Thank you!

**Comment by andrjohns** [comment]
They allow you to choose different colours for when the outlying point is in a positive direction (i.e., the process is improving) or a negative direction (i.e., process is deteriorating), based on the "Improvement Direction" dropdown option. If the direction or differentiation between improvement vs. deterioration isn't relevant for you, then just use the same colour for both.

Are you wanting to highlight points based on the specification limits instead of the control limits? That isn't supported at the moment, I'll add an option and let you know

**Comment by andrjohns** [comment]
The development version of the visual now supports highlighting astronomical points using the specification limits instead of the control limits:

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/f4b861c7-1a93-401e-aba0-008b30cc97ef)
